ShopThuCungMVC/Models/Blog.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ShopThuCungMVC.Models
{
    public class Blog
    {
        private int v1;
        private string v2;
        private object value1;
        private object value2;
        private object value3;
        private string userid;
        private object value4;

        public string BlogId { get; set; }
        public string BlogName { get; set;}
        public int Status { get; set;}
        public string Image { get; set;}
        public string Desription { get; set;}
        public string Dital { get; set; }
        public string CreateBy { get; set; }
        public string CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public string UpdateDate { get; set; }

        public Blog(string blogId, string blogName, int status, string image, string desription, string Dital, string createBy, string createDate, string updateBy, string updateDate)
        {
            BlogId = blogId;
            BlogName = blogName;
            Status = status;
            Image = image;
            Desription = desription;
            this.Dital = Dital;
            CreateBy = createBy;
            CreateDate = createDate;
            UpdateBy = updateBy;
            UpdateDate = updateDate;
        }

        public Blog(string blogId, string blogName, int v1, string v2, object value1, object value2, object value3, string userid, object value4)
        {
            BlogId = blogId;
            BlogName = blogName;
            this.v1 = v1;
            this.v2 = v2;
            this.value1 = value1;
            this.value2 = value2;
            this.value3 = value3;
            this.userid = userid;
            this.value4 = value4;
        }
    }
}

ShopThuCungMVC/Models/Contact.cs
using System.ComponentModel.DataAnnotations;

namespace ShopThuCungMVC.Models
{
    public class Contact
    {
        [Key]
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string detail { get; set; }
        public int status { get; set; }

        public Contact(int id, string name, string email, string detail, int status)
        {
            this.id = id;
            this.name = name;
            this.email = email;
            this.detail = detail;
            this.status = status;
        }
    }
}

ShopThuCungMVC/Areas/Admin/Controllers/BlogController.cs
using ShopThuCungMVC.Models;
using ShopThuCungMVC.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopThuCungMVC.Areas.Admin.Controllers
{
    public class BlogController : Controller
    {
        public ActionResult Blogs()
        {
            UserAccount account = (UserAccount)Session["admin"];
            if (account != null)
                return View();
            else
                return RedirectToAction("Login", "Auth");
        }

        [HttpGet]
        public ActionResult AddBlog()
        {
            UserAccount account = (UserAccount)Session["admin"];
            if (account != null)
                return View();
            else
                return RedirectToAction("Login", "Auth");
        }

        [HttpPost]
        public ActionResult AddBlog(string userid, string name, string desc, HttpPostedFileBase file)
        {
            UserAccount account = (UserAccount)Session["admin"];
            if (account != null)
            {
                UploadFile(file);
                string _FileName = Path.GetFileName(file.FileName);
               /* BlogCateService.AddBlog(userid, name, _FileName, desc);*/
                return RedirectToAction("Blog", "Admin/Blog");
            }
            else
                return RedirectToAction("Login", "Auth");
        }

        public void UploadFile(HttpPostedFileBase file)
        {
            try
            {
                string _path = null;
                if (file.ContentLength > 0)
                {
                    string _FileName = Path.GetFileName(file.FileName);
                    _path = Path.Combine(Server.MapPath("~/Content/img/products"), _FileName);
                    file.SaveAs(_path);
                }
            }
            catch
            {
            }
        }


    }
}

ShopThuCungMVC/Controllers/DetailsController.cs
<<<<<<< HEAD
﻿using Antlr.Runtime.Misc;
using ShopThuCungMVC.Models;
=======
﻿using ShopThuCungMVC.Models;
>>>>>>> 93e37e9fd386e73b6fcb4f753603c8e5333b55bc
using ShopThuCungMVC.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopThuCungMVC.Controllers
{
	public class DetailsController : Controller
	{
		public ActionResult BlogDetails(string id)
		{
			if (id == null)
			{
                return RedirectToAction("Blog", "Home");
            }
            Blog blog = BlogsService.BlogById(id);
            return View(blog);
		}
<<<<<<< HEAD

		public ActionResult ProductDetails(String id)
       /* public ActionResult ProductDetails()*/
=======
		public ActionResult ProductDetails(String id)
>>>>>>> 93e37e9fd386e73b6fcb4f753603c8e5333b55bc
		{
			if (string.IsNullOrEmpty(id))
			{
                return RedirectToAction("AllProduct", "Home");
            }
			Product detail = Services.ProductCateService.Detail(id);
			return View(detail);
		}

		public ActionResult Filter(string order_by, String cate_id
			, String price, String size, String search)
		{
			List<Product> filter = ProductCateService.Filter(order_by, cate_id, price, size, search);
			return View(filter);
		}
    }
}

ShopThuCungMVC/Controllers/HomeController.cs
using Microsoft.Extensions.Logging;
using MySqlX.XDevAPI.Common;
using Org.BouncyCastle.Utilities;
using ShopThuCungMVC.Models;
using ShopThuCungMVC.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopThuCungMVC.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Blog()
        {

            return View();
        }
        public ActionResult AllProduct(String Id)
        {
            if (Id == null)
            {
                List<Product> listProductById = ProductCateService.listAllProduct();
                return View(listProductById);
            }
            else
            {
                List<Product> listProductById = ProductCateService.listProductbyCate(Id);
                return View(listProductById);
            }
        }
        public JsonResult LoadMoreProduct(string id, int page, String price, String size, String orderby)
        {
            if (id.Equals("AllProduct"))
            {
                List<Product> listProductById = ProductCateService.Filter(price, id, size, orderby).Skip(page * 6).Take(6).ToList();
                return Json(new { data = listProductById }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                List<Product> listProductById = ProductCateService.Filter(price, id, size, orderby).Skip(page * 6).Take(6).ToList();
                return Json(new { data = listProductById }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult Contact()
        {
            return View();
        }
        public ActionResult Policy()
        {
            return View();
        }
        public JsonResult Filter(String price, String category, String size, String orderby)
        {
            List<Product> list = ProductCateService.Filter(price, category, size, orderby);
            return Json(new { data = list, count = list.Count }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult listCate(String category)
        {
            return View();
        }
        public ActionResult listProCateClassify(String id)
        {
            return View();
        }
    }
}

ShopThuCungMVC/Views/Home/Blog.cshtml
@{
    ViewData["Title"] = "Blog";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}

<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-section set-bg" data-setbg="https://localhost:44322/Content/img/breadcrumb.jpg" style="background-image: url(&quot;img/breadcrumb.jpg&quot;);">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="breadcrumb__text">
                    <h2>Tin tức</h2>
                    <div class="breadcrumb__option">
                        <a href="@Url.Action("Index", "Home")">Trang chủ</a>
                        <span><strong>Tin tức</strong></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->
<!-- Blog Section Begin -->
<section class="blog spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-5">
                <div class="blog__sidebar" style="padding: 20px;">
                   
                    <div class="blog__sidebar__item">
                        <h4>Tin mới nhất</h4>
                        <div class="blog__sidebar__recent">
                            @{
                                List<ShopThuCungMVC.Models.Blog> listB = ShopThuCungMVC.Services.BlogsService.get3BlogNew();
                                foreach (var item in listB)
                                {
                                    <div class="blog__sidebar__recent__item">
                                            <img src="@item.Image" alt="">
                                            <h5>@Html.ActionLink(item.BlogName, "BlogDetails", "Details", new { @Id = item.BlogId }, new {@style="color: black; font-size: 15px;"})</h5>
                                            <span style="color: black; font-size: 15px;">@item.CreateDate</span>
                                    </div>
                                }
                            }
                        </div>
                    </div>
                   
                </div>
            </div>
            <div class="col-lg-8 col-md-7">
                <div class="row">
                    @{
                        List<ShopThuCungMVC.Models.Blog> list = ShopThuCungMVC.Services.BlogsService.listBlog();
                        foreach (var item in list)
                        {
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="blog__item">
                                    <div class="blog__item__pic">
                                        <img src="@item.Image" alt="">
                                    </div>
                                    <div class="blog__item__text">
                                        <ul>
                                            <li><i class="fa fa-calendar-o"></i> @item.CreateDate</li>

                                        </ul>
                                        <h5>@Html.ActionLink(item.BlogName, "BlogDetails", "Details", new { @Id = item.BlogId }, null)</h5>
                                        <p>@item.Desription</p>
                                        
                                        @*<a href="blog-details.html" class="blog__btn">ĐỌC THÊM <span class="arrow_right"></span></a>*@
                                    </div>
                                </div>
                            </div>

                           
                        }
                    }
                    

                    <div class="col-lg-12">
                        <div class="product__pagination blog__pagination">
                            <a href="#">1</a>
                            <a href="#">2</a>
                            <a href="#">3</a>
                            <a href="#"><i class="fa fa-long-arrow-right"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Blog Section End -->

ShopThuCungMVC/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}

<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-section set-bg" data-setbg="https://localhost:44322/Content/img/breadcrumb.jpg" style="background-image: url(&quot;img/breadcrumb.jpg&quot;);">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="breadcrumb__text">
                    <h2>Contact Us</h2>
                    <div class="breadcrumb__option">
                        <a href="@Url.Action("Index", "Home")">Trang chủ</a>
                        <span><strong>Liên hệ</strong></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->
<!-- Contact Section Begin -->
<section class="contact spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-6 text-center">
                <div class="contact__widget">
                    <span class="icon_phone"></span>
                    <h4>Điện thoại</h4>
                    <p>+85 987.145.xxx</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 text-center">
                <div class="contact__widget">
                    <span class="icon_pin_alt"></span>
                    <h4>Địa chỉ</h4>
                    <p>TP.HCM, Việt Nam</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 text-center">
                <div class="contact__widget">
                    <span class="icon_clock_alt"></span>
                    <h4>Giờ mở cửa</h4>
                    <p>7:00 am đến 23:00 pm</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 text-center">
                <div class="contact__widget">
                    <span class="icon_mail_alt"></span>
                    <h4>Email</h4>
                    <p>LTW_nhom10@gmail.com</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Contact Section End -->
<!-- Map Begin -->
<div class="map">
    <!-- <iframe
        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d49116.39176087041!2d-86.41867791216099!3d39.69977417971648!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x886ca48c841038a1%3A0x70cfba96bf847f0!2sPlainfield%2C%20IN%2C%20USA!5e0!3m2!1sen!2sbd!4v1586106673811!5m2!1sen!2sbd"
        height="500" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0">
    </iframe> -->
    <div style="width: 100%"><iframe width="100%" height="500" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?width=100%25&amp;height=100%25&amp;hl=en&amp;q=Tr%C6%B0%E1%BB%9Dng%20%C4%90%E1%BA%A1i%20h%E1%BB%8Dc%20N%C3%B4ng%20L%C3%A2m+(My%20Business%20Name)&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"><a href="https://www.gps.ie/sport-gps/">hiking gps</a></iframe></div>
    <div class="map-inside">
        <i class="icon_pin"></i>
        <div class="inside-widget">
            <h4>Đại Học Nông Lâm</h4>
            <ul>
                <li>Điện thoại: +85 987.145.xxx</li>
                <li>Địa chỉ: Thủ Đức, TP.HCM, Việt Nam</li>
            </ul>
        </div>
    </div>
</div>
<!-- Map End -->
<!-- Contact Form Begin -->
<div class="contact-form spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="contact__form__title">
                    <h2>Mọi thắc mắc xin liên hệ: </h2>
                </div>
            </div>
        </div>
        <form action="#">
            <div class="row">
                <div class="col-lg-6 col-md-6">
                    <input type="text" placeholder="Họ và tên">
                </div>
                <div class="col-lg-6 col-md-6">
                    <input type="text" placeholder="Email">
                </div>
                <div class="col-lg-12 text-center">
                    <textarea placeholder="Lời nhắn"></textarea>
                    <button type="submit" class="site-btn">GỬI TIN NHẮN</button>
                </div>
            </div>
        </form>
    </div>
</div>
<!-- Contact Form End -->

ShopThuCungMVC/Views/Home/Index.cshtml
@using ShopThuCungMVC.Models;
@using ShopThuCungMVC.Services;
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";
}

    <!-- Hero Section Begin -->
    <!-- example for run value-->
    <!-- Categories Section Begin -->
    <section class="categories">
        <div class="container">
            <div class="row">
                <div class="categories__slider owl-carousel">
                    <div class="col-lg-3">
                        <div class="categories__item set-bg" data-setbg="https://localhost:44322/Content/img/categories/cat-5.jpg">
                            <h5><a href="#">Mèo Lông Xám</a></h5>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="categories__item set-bg" data-setbg="https://localhost:44322/Content/img/categories/cat-6.jpg">
                            <h5><a href="#">Mèo Chân Ngắn</a></h5>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="categories__item set-bg" data-setbg="https://localhost:44322/Content/img/categories/cat-3.jpg">
                            <h5><a href="#">Chó Poodle</a></h5>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="categories__item set-bg" data-setbg="https://localhost:44322/Content/img/categories/cat-4.jpg">
                            <h5><a href="#">Chó Shiba</a></h5>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="categories__item set-bg" data-setbg="https://localhost:44322/Content/img/categories/cat-2.jpg">
                            <h5><a href="#">Mèo Lông Ngắn</a></h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Categories Section End -->
    <!-- Featured Section Begin -->
    <section class="featured spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title">
                        <h2>Sản Phẩm Bán Chạy</h2>
                    </div>
                </div>
            </div>
            <div class="row featured__filter">
                @{
                    List<ShopThuCungMVC.Models.Product> listPD = ShopThuCungMVC.Services.ProductCateService.getTop8BestSelling();
                    foreach (var item in listPD)
                    {
                        <div class="col-lg-3 col-md-4 col-sm-6 mix oranges fresh-meat">
                            <div class="featured__item">
                                <div class="featured__item__pic set-bg" data-setbg="@item.Image">
                                    <ul class="featured__item__pic__hover"  style="cursor:pointer">
                                        @if (Session["user"] == null)
                                        {
                                            <li><a href="@Url.Action("Login", "User")"><i class="fa fa-shopping-cart" style="cursor:pointer"></i></a></li>
                                        }
                                        else
                                        {
                                            <li><a class="btnAddToCart" data-id="@item.productId"><i class="fa fa-shopping-cart"></i></a></li>
                                        }
                                    </ul>
                                </div>
                                <div class="featured__item__text">
                                    <h6>@Html.ActionLink(item.ProductName, "ProductDetails", "Details", new { @Id = item.productId }, null)</h6>
                                    <h5>@item.Price</h5>
                                </div>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    </section>
    <!-- Featured Section End -->
    <!-- Banner Begin -->
    <div class="banner">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="banner__pic">
                        <img src="img/banner/banner-1.jpg" alt="">
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="banner__pic">
                        <img src="img/banner/banner-2.jpg" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Blog Section Begin -->
    <section class="from-blog spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title from-blog__title">
                        <h2>Bài Viết Bạn Có Thể Thích</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                @{
                    List<Blog> listB = ProductCateService.get3Blog();
                    foreach (var item in listB)
                    {

                        <div class="col-lg-4 col-md-4 col-sm-6">
                            <div class="blog__item">
                                <div class="blog__item__pic">
                                    <img src="@item.Image" alt="">
                                </div>
                                <div class="blog__item__text">
                                    <ul>
                                        <li><i class="fa fa-calendar-o"></i>@item.CreateDate</li>
                                    </ul>
                                    <h5>@Html.ActionLink(item.BlogName, "BlogDetails", "Details", new { @Id = item.BlogId }, null)</h5>
                                    <p>@item.Desription</p>
                                </div>
                            </div>
                        </div>

                    }
                }
            </div>
        </div>
        
        </section>
    <!-- Blog Section End -->
    <script src="~/Scripts/jquery-3.6.1.js"></script>
    <script>
        $(document).ready(function () {
            $('.featured__item').on('click', '.btnAddToCart', function (e) {
                e.preventDefault();
                var id = $(this).data('id');
                var quantity = 1;
                $.ajax({
                    url: '/ProductBag/AddToCart',
                    type: 'POST',
                    data: { id: id, quantity: quantity },
                    success: function (rs) {
                        const formatter = new Intl.NumberFormat('vn-VN');
                        $(".header__cart ul li a span").text(rs.quantity)
                        $(".header__cart__price span").text(formatter.format(rs.total) + "₫")
                    }
                })
            })
        })
    </script>