ShopThuCungMVC/Areas/Admin/Controllers/AccessoryController.cs
using ShopThuCungMVC.Models;
using ShopThuCungMVC.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;

namespace ShopThuCungMVC.Areas.Admin.Controllers
{
    public class AccessoryController : Controller
    {
        public ActionResult Accessories()
        {
            List<Product> listProductById = ProductCateService.listProductAccessorybyCate(null);
            UserAccount account = (UserAccount)Session["admin"];
            if (account != null)
                return View(listProductById);
            else
                return RedirectToAction("Login", "Auth");
        }
        public void UploadFile(HttpPostedFileBase file)
        {
            try
            {
                string _path = null;
                if (file != null)
                {
                    if (file.ContentLength > 0)
                    {
                        string _FileName = Path.GetFileName(file.FileName);
                        _path = Path.Combine(Server.MapPath("~/Content/img/products"), _FileName);
                        file.SaveAs(_path);
                    }
                }
            }
            catch
            {
            }
        }
        [HttpGet]
        public ActionResult AddAccessory(String pid)
        {
            UserAccount account = (UserAccount)Session["admin"];
            if (account != null)
            {
                if (pid != null)
                {
                    Product product = ProductCateService.Detail(pid);
                    return View(product);
                }
                else
                {
                    return View();
                }
            }
            else
                return RedirectToAction("Login", "Auth");
        }
        [HttpPost]
        public ActionResult AddAccessory(string productid, string userid, string productname, string desc, HttpPostedFileBase file, string price, string promoPrice, string quantity, string date, string giong, string size)
        {
            UserAccount account = (UserAccount)Session["admin"];
            if (account != null)
            {
                if (productid != null)
                {
                    UploadFile(file);
                    string _FileName = "";
                    if (file != null)
                    {
                        _FileName = Path.GetFileName(file.FileName);
                    }
                    ProductCateService.UpdateAccessory(productid, userid, productname, _FileName, desc, price, promoPrice, quantity, date, giong, size);
                    return RedirectToAction("Accessories", "Admin/Accessory");
                }
                else
                {
                    UploadFile(file);
                    string _FileName = "";
                    if (file != null)
                    {
                        _FileName = Path.GetFileName(file.FileName);
                    }
                    ProductCateService.AddNewAccessory(userid, productname, _FileName, desc, price, promoPrice, quantity, date, giong, size);
                    return RedirectToAction("Accessories", "Admin/Accessory");
                }
            }
            else
                return RedirectToAction("Login", "Auth");
        }
        public ActionResult DeleteProduct(string pid)
        {
            if (pid != null)
            {
                ProductCateService.DeleteProduct(pid);
                return Json(new { status = true });
            }
            else
            {
                return Json(new { status = false });
            }
        }
    }
}

ShopThuCungMVC/Areas/Admin/Views/Accessory/Accessories.cshtml
@model List<ShopThuCungMVC.Models.Product>
@{
    ViewData["Title"] = "Accessories";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@section stylesheet {

    <link rel="stylesheet" href="@Url.Content("~/Content/AdminResources/assets/css/list/style1.css")" />
    <link rel="stylesheet" href="@Url.Content("~/Content/AdminResources/assets/css/list/bootstrap1.min.css")" />
    <link rel="stylesheet" href="@Url.Content("~/Content/AdminResources/assets/css/style.css")" id="main-style-link">
}

<!-- [ Main Content ] start -->
<div class="pc-container">
    <div class="pcoded-content">
        <!-- [ breadcrumb ] start -->
        <div class="page-header">
            <div class="page-block">
                <div class="row align-items-center">
                    <div class="col-md-6">
                        <!-- <div class="page-header-title">
                          <h5 class="m-b-10">Dashboard sale</h5>
                        </div> -->
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item">Quản lý sản phẩm</li>
                            <li class="breadcrumb-item">Phụ kiện</li>
                            <li class="breadcrumb-item">Danh sách phụ kiện</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- [ breadcrumb ] end -->
        <!-- [ Main Content ] start -->
        <div class="row">
            <div class="row">
                <h2 style=" font-weight: 800; text-align: center; margin: 10px 0px 40px;">Danh sách phụ kiện</h2>
                @foreach (var item in Model)
                {
                    <div class="col-md-3">
                        <div class="white_card position-relative mb_20">
                            <div class="card-body">
                                <img src="@item.Image"
                                     alt=""
                                     class="d-block mx-auto my-4"
                                     height="150" />
                                <div class="row my-4">
                                    <div class="col">
                                        <!-- <span class="badge_btn_3 mb-1" style="margin-left: 63px;">Chó Phốc</span> -->
                                        <a href="#" class="f_w_400 color_text_3 f_s_14 d-block"
                                           style="text-align: center;">@item.ProductName</a>
                                    </div>
                                    <div class="col-auto">
                                        <h4 class="text-dark mt-0" style="margin-left: 65px;">
                                            @item.Price đ

                                        </h4>
                                        <ul class="list-inline mb-0 product-review align-self-center" style="margin-left: 35px;">
                                            <li class="list-inline-item">
                                                <i class="fas fa-star text-warning font-16"></i>
                                            </li>
                                            <li class="list-inline-item">
                                                <i class="fas fa-star text-warning font-16 ms -n2"></i>
                                            </li>
                                            <li class="list-inline-item">
                                                <i class="fas fa-star text-warning font-16 ms -n2"></i>
                                            </li>
                                            <li class="list-inline-item">
                                                <i class="fas fa-star text-warning font-16 ms -n2"></i>
                                            </li>
                                            <li class="list-inline-item">
                                                <i class="fas fa-star-half text-warning font-16 ms -n2"></i>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="d-grid">
                                    @Html.ActionLink("Sửa sản phẩm", "AddAccessory", "Accessory", new { @pid = item.productId }, new { @class = "btn_2 edit", @style = "margin-top: 3px; text-align: center; color: red; cursor: pointer;" })
                                    <button class="btn_2 delete" id="remove-@item.productId" style="margin-top: 3px; text-align: center;">Xóa</button>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<!-- [ Main Content ] end -->
<script src="~/Content/js/jquery-3.3.1.min.js"></script>
<script>
    function deleteupdate() {
        $(".delete").each(function () {
            $(this).click(function (e) {
                e.preventDefault();
                const pid = $(this).attr("id").substr(7);
                $.ajax({
                    url: "/Accessory/DeleteProduct",
                    type: "post",
                    data: {
                        pid: pid
                    },
                    success: function (result) {
                        if (result.status) {
                            alert("xóa sản phẩm thành công");
                            location.reload();
                        } else {
                            alert("Không có productid để xóa");
                        }
                    }
                })
            })
        })
    }
    $(document).ready(function(){
        deleteupdate();
    })
</script>